version: '3.5'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    command: bash -c "npm run seed && npm run start:dev"
#    command: npm run start:dev
    environment:
      NODE_ENV: development
      PORT: 3000
#    network_mode: "host"
    volumes:
      - ./api/src:/app/api/src
    ports:
      - "8000:3000"
    depends_on:
      - postgres
      - minio
      # - configurator

  # configurator:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./configurator
  #   command: npm run start
  #   environment:
  #     NODE_ENV: development
  #     PORT: 3000
  #   volumes:
  #     - ./configurator/src:/app/src
  #   ports:
  #     - "8000:3000"

  postgres:
    image: postgres:15.0
    environment:
      POSTGRES_USER: nest_test
      POSTGRES_PASSWORD: nest_test
      POSTGRES_DB: nest_test
      PGDATA: /data/postgres
    volumes:
       - postgres:/var/www/nest_test/docker-volumes/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: nest_test@admin.com
      PGADMIN_DEFAULT_PASSWORD: nest_test
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
       - pgadmin:/var/www/nest_test/docker-volumes/pgadmin
    ports:
      - "127.0.0.1:5050:80"
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio-data:/data

  createbucket:
    image: minio/mc:latest
    container_name: createbucket
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add --api s3v4 s3 http://minio:9000 minio minio123;
      /usr/bin/mc mb s3/images;
      /usr/bin/mc anonymous set public s3/images;
      "

volumes:
  postgres:
  pgadmin:
  minio-data:
