version: '3.5'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    command: bash -c "npm run seed && npm run start:dev"
#    command: npm run start:dev
    environment:
      NODE_ENV: development
      PORT: 3000
#    network_mode: "host"
    volumes:
      - ./api/src:/app/api/src
    ports:
      - "8000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    links:
      - postgres
      - minio
      - configurator

  configurator:
     build:
       dockerfile: Dockerfile
       context: configurator
     command: npm run dev
     ports:
       - "5000:5000"
     environment:
       NODE_ENV: development
       PORT: 5000
     volumes:
       - ./configurator/src:/app/src

  postgres:
    image: postgres:15.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
       - postgres:/var/www/postgres/docker-volumes/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    entrypoint: >
      /bin/sh -c '
        isAlive() { curl -sf http://minio:9000/minio/health/live; }
        minio $$0 "$$@" --quiet & echo $$! > /tmp/minio.pid
        until isAlive; do sleep 1; done
        echo "MinIO is ready. Proceeding with setup..."
        mc alias set myminio http://minio:9000 minio minio123
        mc mb myminio/images/ --ignore-existing
        mc anonymous set public myminio/images
        kill -s INT $$(cat /tmp/minio.pid) && rm /tmp/minio.pid
        while isAlive; do sleep 0.1; done
        exec minio $$0 "$$@"
        '
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - minio-data:/data

volumes:
  postgres:
  pgadmin:
  minio-data:
