name: Deploy Frontend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@master

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          port:  ${{ secrets.SSH_PORT }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo chown -R ${{ secrets.SSH_USERNAME }} /home/energet/energet-backend/
            git config --global --add safe.directory /home/energet/energet-backend/
            cd /home/energet/energet-backend/
            sudo docker compose down || exit 1
            git checkout ${{ github.ref_name }} || exit 1
            sudo git pull || exit 1
            sudo docker compose build || exit 1
            sudo docker compose up -d || exit 1

      - name: Send Telegram Message
        if: failure()
        env:
          message: |
            ❗ Произошла ошибка во время деплоя
            
            🔗 Ссылка на пайплайн 🔗
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          msg_text='$message'
          curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=${msg_text}&reply_to_message_id=${{ secrets.TELEGRAM_TOPIC_ID }}"

      - name: Send Telegram Message
        if: success()
        env:
          MESSAGE: |
            ✅ Изменения успешно задеплоены

            🔗 Ссылка на прод 🔗
            ${{ secrets.PRODUCTION_URL || 'Отсутствует' }}
        run: |
          curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=$MESSAGE&reply_to_message_id=${{ secrets.TELEGRAM_TOPIC_ID }}"
