name: Deploy Frontend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4.2.2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          echo "sadf"

      - name: Отправка в тг чат сообщения если пайплайн упал
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❗ Произошла ошибка во время деплоя
            
            🔗 Ссылка на пайплайн 🔗
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Отправка в тг чат сообщения если пайплайн завершился успешно
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ Изменения успешно задеплоены
            
            🔗 Ссылка на прод 🔗
            ${{ secrets.PRODUCTION_URL || 'Отсутствует' }}
